package cipher;

public class MainMenu {

	public static void main(String[] args) {
		FrequencyAnalysis FA = new FrequencyAnalysis();
		
		String cipherText = "";
		cipherText = "HSCOE CYASX FPRCP ZJEFW WTCGR JHHSC PFECY ZHPZJ EOETC YNGHS CPBWF YHZTY OTWHE FHCHS CEFHT WTYCG FYNHZ HEPHZ HJEYH SCSTI SKFWJ CHFEI CHGOZ EHSCX GCWKC GHSCP SFKCF BFEHT AJWFE TYHCE CGHTY YFQTG ATCYH TGHGO EZXHS CNTCF WASCX TGHCY BEZUC AHTOP ZJLFY HHZRE CFVHS CECTA SGNZV HZEYC HLZEV RCOZE CHSCP AFYNZ GZHFV CAFEC YZHHZ GSFEC FYPTY HCWWT ICYAC LTHSH SCXPZ JSFKC RCCYL FEYCN THSTY VTHTG HTXCH ZRCIT YYCIZ HTFHT ZYGTS FKCFY JXRCE TYXTY NFYNT HSTYV ZYACP ZJVYZ LLSFH TFXZO OCETY IPZJL TWWOT YNTHK CEPEC FGZYF RWCFG FGTIY ZOIZZ NOFTH STZOO CEPZJ HSCOZ WWZLT YITYO ZEXFH TZYZY CZOHS CWZAF WEFHT WTYCA ZZENT YFHZE GLTWW RCWCF KTYIH SCJGG CAHZE HZXZE EZLYT ISHTY FRWFA VWTXZ JGTYC JYNCE HSCRF AVGCF HZOST GAFEP ZJLTW WOTYN STNNC YFUJY TZEGG ZOOTA CELSZ TGHEP TYIHZ CGAFB CFYNT YHSCH EJYVP ZJLTW WOTYN FYJXR CEZOB FBCEG ECWFH TYIHZ GHZWC YFEHL ZEVGH SFHSC SZBCG HZHEF NCHZH SCOEC YASOZ ESTGO ECCNZ XPZJX TISHL FYHHZ AZYGT NCEAF ECOJW WPLSC HSCEP ZJAFY HEJGH PZJEO ETCYN ASFEW TCLTH SHSTG TYOZE XFHTZ YFOHC EFWWS CESJG RFYNO EFYAZ TGTGO ECYAS ";
		
				
		cipherText = cipherText.toUpperCase(); // Make ciphertext uppercase
		System.out.println("Ciphertext: " + cipherText);
		
		 // Single character only
		FA.singCharAnal(cipherText); 		
		
		// Double characters
		// FA.doubCharAnal(cipherText);
		
		/*CEqualsFY CE = new CEqualsFY();
		String p = CE.genCTAlphabet(cipherText, 5, 7);
		System.out.println("ABCDEFGHIJKLMNOPQRSTUVWNXYZ");
		System.out.println(p);*/
	}

}
